title: Lea Laukstein STYLE
url: https://lea.laukstein.com
enforce_ssl: lea.laukstein.com
permalink: /:categories/:title

timezone: UTC
markdown: kramdown
sass:
    style: compressed
compress_html:
    clippings: all
    comments: ["<!-- ", " -->"]
    endings: all
    profile: false
    startings: [html, head, body]
