title: סטיילינג לדתיות — לאה לאוקשטיין
url: https://lea.laukstein.com
enforce_ssl: lea.laukstein.com
permalink: /:category/:title
assets: /assets/
timezone: UTC
safe: true
include: [_pages]
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: true
sass:
    sass_dir: assets
    style: compressed
compress_html:
    clippings: all
    comments: ["<!-- ", " -->"]
    endings: all
    profile: false
    startings: [html, head, body]
webrick:
    headers:
        Referrer-Policy: no-referrer
        X-Frame-Options: SAMEORIGIN
        X-XSS-Protection: 1
whitelist:
    - jekyll-redirect-from
plugins:
    - jekyll-redirect-from
exclude:
    - CNAME
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - node_modules
    - /*README.md
    - ~*
