title: סטיילינג לדתיות – לאה לאוקשטיין
description: לאה לאוקשטיין סטייליסטית אישית מומחית בסטיילינג לדתיות, ליוויתי עשרות נשים בתהליכי סטיילינג שונים, סדנאות סטיילינג, סידור ארון, סיבוב קניות, קורסים בסטיילינג אינטרנטי. נשים יצאו בטוחות בעצמן וביופי שלהן, עם ארון בגדים מצומצם אך מדויק. הן יודעות איך לעשות קניית נכון ויעיל.
url: https://lea.laukstein.com
enforce_ssl: lea.laukstein.com
permalink: /:category/:title
assets: /assets/
github: [metadata]
repository: laukstein/lea.laukstein.com
# environment: development
timezone: UTC
safe: true
theme: false
future: true
collections:
    pages:
        output: true
        permalink: /:path
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: true
excerpt_separator: "\n"
sass:
    sass_dir: assets
    style: compressed
compress_html:
    clippings: all
    comments: ["<!-- ", " -->"]
    endings: all
    profile: false
    startings: [html, head, body]
# webrick:
#     headers:
#         Referrer-Policy: no-referrer
#         X-Frame-Options: SAMEORIGIN
#         X-XSS-Protection: 1
whitelist:
    - jekyll-redirect-from
plugins:
    - jekyll-redirect-from
exclude:
    - CNAME
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - node_modules
    - package.json
    - vendor/*
    - /*README.md
    - .*
    - ~*
