title: סטיילינג לדתיות — לאה לאוקשטיין
url: https://lea.laukstein.com
enforce_ssl: lea.laukstein.com
permalink: /:categories/:title
assets: /assets/
timezone: UTC
include: ['_pages']
safe: true
markdown: kramdown
sass:
    style: compressed
compress_html:
    clippings: all
    comments: ["<!-- ", " -->"]
    endings: all
    profile: false
    startings: [html, head, body]
webrick:
    headers:
        Content-Security-Policy: referrer no-referrer
        X-Frame-Options: DENY
        X-XSS-Protection: 1
whitelist:
    # - jekyll-sitemap
    - jekyll-redirect-from
gems:
    # - jekyll-sitemap
    - jekyll-redirect-from
