products:
    - name: online
      title: קורסים בסטיילינג
    - name: stylist
      title: לסטייליסטיות

product:
    - name: title
    - name: duration
      title: אורך
    - name: price
      title: ההשקעה
    - name: location
      title: מיקום
    - name: extra
      title: בונוס
    - name: fit
      title: מתאים ל
      more: true
    - name: details
      title: תיאור התהליך
      more: true
    - name: goals
      title: מה נלמד
      more: true
    - name: takeWith
      title: את יוצאת עם
      more: true
    - name: buttonType
      title: כפתור
      more: true
